### ISSUE TITLE
port forkserver to afl-cmin

### ISSUE THREAD

**Issue by korniltsev** [vanhauser-thc/AFLplusplus#168]
I have a fuzzer with a pretty long initial setup (unicorn mode, 100mb of modules, ~1m to init total)
And corpus minimization takes forever without .
Do you think this could be a reasonable idea to port forkserver to afl-cmin ( similar to afl-tmin,
https://github.com/nccgroup/TriforceAFL/) ?

**Comment by domenukk** [comment]
Sounds like an excellent idea and should be considered while we already discuss how afl cmin should be implemented going forward in issue #163 ...

**Comment by hexcoder-** [comment]
Yes, good idea, but at first we would need a rewrite.

**Comment by domenukk** [comment]
Maybe passing a list of input files and handling the `@` commandline args in showmap just like AFL, then having a showmap output directory, could be the way to go

**Comment by vanhauser-thc** [comment]
if a rewrite of afl-cmin in C is based on afl-trim it should be rather easy and fast to do

**Comment by hexcoder-** [comment]
In the current scheme the fork server functionality would only be needed in `afl-showmap` when traces are collected in STEP 1. The other steps just operate on the traces (and could be massively optimized).

@vanhauser-thc: What is afl-trim? Something external? Or do you mean afl-tmin?

I would like to merge the code base from afl-tmin, afl-fuzz and afl-showmap, so we don't have to duplicate code and can benefit from fork server. The other steps of afl-cmin can be done separately either in C or as a script IMHO.

**Comment by vanhauser-thc** [comment]
I meant afl-tmin ;)

but yeah another solution would be that afl-showmap gets the -I (capital -i option) to read all files in from a directory and so we would not need to code an afl-cmin C code based tool

**Comment by hexcoder-** [comment]
@vanhauser-thc: I agree. That would  be the smartest thing to do.
So this is my roadmap:

1. add -I to `afl-showmap`, which loops through files and gathers tuples in memory.
2. add minimization logic to `afl-showmap` activated by -I or when name is `afl-cmin`, which copies smallest files to output directory
3. rename `afl-cmin` to `afl-cmin.old`
4. create a link `afl-cmin` to `afl-showmap` (for compatibility)
5. optimization: add fork server functionality to `afl-showmap`

**Comment by vanhauser-thc** [comment]
or you make it less complex: -I just collects the map for all files in the input directory - same as afl-cmin is doing.
and shell/awk logic in afl-cmin is doing the sort etc.
this way afl-showmap has additional value to get tuple information for many input files at once - and it is less work to implement.

**Comment by vanhauser-thc** [comment]
added forkserver support in afl-showmap -> @hexcoder- now you just need to add this feature into your awk script :)

basically: -i inputdir -o outputdir 

currently the outputdir data is kept, so files are added or overwritten, existing stuff is not wiped. filename stays the same (might be confusing? maybe add .txt? afl-cmin has to know the extension though)

**Comment by hexcoder-** [comment]
Great news!

I noticed that  options '-A' and '-i' are mutually exclusive in afl-showmap.
You could add a check. (-A sets the input filename in cmin_mode)

I prepared afl-cmin (awk version) to call afl-showmap with the new -i mode,
but the build is currently broken. So I cannot test right now.

You support only the '@@' variant, right?
So for stdin input processing I left the old slow method in.

Heiko

**Comment by vanhauser-thc** [comment]
Yeah the check for -A/-i is missing
stdin should work - but havent tried :) had to exit on the train

**Comment by hexcoder-** [comment]
I just adjusted afl-cmin to use forkserver_mode when input files are used (target arguments contain '@@'). Also changed the test script to test this mode  -> https://github.com/vanhauser-thc/AFLplusplus/commit/f676e5528ac8a2d454a607fceaa8590f11b9f795. Looks good so far.

forkserver_mode with stdin input is investigated later (have to ask @vanhauser-thc something)

@korniltsev: Please test and report back, thanks.

**Comment by hexcoder-** [comment]
stdin does not work yet:
Running this in directory `test` 
`AFL_CMIN_ALLOW_ANY=1 ../afl-showmap -m 200 -t none -o in2/.traces -Z -i in -- ./test-instr.plain`
gives
```
[*] Spinning up the fork server...
[+] All right - fork server is up.
000000000000000000000000

[-]  SYSTEM ERROR : ftruncate() failed
    Stop location : write_to_testcase(), src/afl-showmap.c:272
       OS message : Invalid argument

```

When in cmin_mode or when -q is given the fork server messages can be suppressed.

**Comment by vanhauser-thc** [comment]
should work now with stdin

**Comment by hexcoder-** [comment]
Yes, it does. I adjusted afl-cmin and the test case with commit 4bcea7b31fcaa9265a1e3f05e5d67d30b32bb32c. From my point of view this issue can be closed.

**Comment by korniltsev** [comment]
I've lost my big corpus so I could test only on small one(214 inputs)
Honestly I don't know how to test if the minimisation is correct, but on 2.60c my corpus minimises to 12 files and on master to 14 files. Were there any other changes except showmap forkserver that could add more coverage(may be new version has less collisions iduno)? 
I also noticed logging is a little bit inconsistent (no new line)
![Screen Shot 2020-02-06 at 14 45 24](https://user-images.githubusercontent.com/331773/73939608-e63cf580-48fa-11ea-9a8b-b025bb4f73de.png)
Thats pretty much all I could help testing.

**Comment by hexcoder-** [comment]
Thanks for your feedback! So we need yet to make sure that we get the same results as before...
Another issue is that we have now additional output lines from afl_forkserver.

**Comment by domenukk** [comment]
@korniltsev Unicorn mode still? I've since rewritten parts of the forkserver, could that influence the results (negatively)?

**Comment by korniltsev** [comment]
Still unicorn. Second question - don't know.

**Comment by domenukk** [comment]
Not using persistent mode though, I guess? Behavior without shouldn't have changed but I'll doublecheck when I find the time.

**Comment by korniltsev** [comment]
persistent_iters=1

**Comment by vanhauser-thc** [comment]
The behavior of alf-showmap did not change (and if there is a bug, all inputs would look like another, so merged to 1 file ;-) ... there is a difference between afl-cmin and afl-cmin.bash (that is the original command of 2.60c).

so if in master afl-cmin and afl-cmin.bash produce a different number of result files, then we have a problem in afl-cmin. can you please test?

if the issue is not in afl-cmin* then it is in a change in unicorn. that would be important for pinpointing the problem.

**Comment by vanhauser-thc** [comment]
@korniltsev - can you please read my comment above and make this quick test and report back? thank you!

**Comment by korniltsev** [comment]
I did the test on d6d2a53 . The results are wired.
```
root@a66aab345d9d:/mnt# ./AFLplusplus/afl-cmin -m none -U -i corpus_huge -o min_test_cmin -- /usr/bin/python  on_data_recv_fuzzer.py @@
corpus minimization tool for afl++ (awk version)

[*] Testing the target binary...
[+] OK, 1 tuples recorded.
[*] Obtaining traces for 214 input files in 'corpus_huge'.
    Processing 214 files (forkserver mode)...[*] Spinning up the fork server...
[+] All right - fork server is up.

[*] Processing traces for input files in 'corpus_huge'.
    Processing file 214/214
[+] Found 491 unique tuples across 214 files.
[+] Narrowed down to 14 files, saved in 'min_test_cmin'.
root@a66aab345d9d:/mnt# ./AFLplusplus/afl-cmin.bash -m none -U -i corpus_huge -o min_test_bash -- /usr/bin/python  on_data_recv_fuzzer.py @@
corpus minimization tool for afl-fuzz by Michal Zalewski

[-] Error: can't find 'afl-showmap' - please set AFL_PATH.
root@a66aab345d9d:/mnt# export AFL_PATH=/mnt/AFLplusplus/
root@a66aab345d9d:/mnt# ./AFLplusplus/afl-cmin.bash -m none -U -i corpus_huge -o min_test_bash -- /usr/bin/python  on_data_recv_fuzzer.py @@
corpus minimization tool for afl-fuzz by Michal Zalewski

[*] Testing the target binary...
[+] OK, 1 tuples recorded.
[*] Obtaining traces for input files in 'corpus_huge'...
    Processing file 213/213...
[*] Sorting trace sets (this may take a while)...
[+] Found 1 unique tuples across 213 files.
[*] Finding best candidates for each tuple...
    Processing file 213/213...
[*] Sorting candidate list (be patient)...
[*] Processing candidates and writing output files...
    Processing tuple 1/1...
[!] WARNING: All test cases had the same traces, check syntax!
[+] Narrowed down to 1 files, saved in 'min_test_bash'.
```

**Comment by hexcoder-** [comment]
Thanks, very much!

Weird, indeed. Only one result can be right.
Could you rerun both tools with AFL_KEEP_TRACES=1
then tar or zip the complete input dir and both output dirs
and finally mail  the archive to me for further analysis?

I try to fix this then, regards,
Heiko
Von: Anatoly Korniltsev <notifications@github.com>
Gesendet: Montag, 17. Februar 2020 15:00
An: vanhauser-thc/AFLplusplus <AFLplusplus@noreply.github.com>
Cc: hexcoder <heiko@hexco.de>; Mention <mention@noreply.github.com>
Betreff: Re: [vanhauser-thc/AFLplusplus] port forkserver to afl-cmin (#168)


I did the test on d6d2a53<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvanhauser-thc%2FAFLplusplus%2Fcommit%2Fd6d2a53087e1d52f32fe6eacf84a72b76927e361&data=02%7C01%7Cheiko.eissfeldt%40siemens.com%7C463da460c1ac44cdc47108d7b3b1a420%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C1%7C637175447849404723&sdata=1eeEPdECAKvoCZgmpRjAWw%2B08Zt1N60wybR2zg8KSyw%3D&reserved=0> . The results are wired.

root@a66aab345d9d:/mnt# ./AFLplusplus/afl-cmin -m none -U -i corpus_huge -o min_test_cmin -- /usr/bin/python  on_data_recv_fuzzer.py @@

corpus minimization tool for afl++ (awk version)



[*] Testing the target binary...

[+] OK, 1 tuples recorded.

[*] Obtaining traces for 214 input files in 'corpus_huge'.

    Processing 214 files (forkserver mode)...[*] Spinning up the fork server...

[+] All right - fork server is up.



[*] Processing traces for input files in 'corpus_huge'.

    Processing file 214/214

[+] Found 491 unique tuples across 214 files.

[+] Narrowed down to 14 files, saved in 'min_test_cmin'.

root@a66aab345d9d:/mnt# ./AFLplusplus/afl-cmin.bash -m none -U -i corpus_huge -o min_test_bash -- /usr/bin/python  on_data_recv_fuzzer.py @@

corpus minimization tool for afl-fuzz by Michal Zalewski



[-] Error: can't find 'afl-showmap' - please set AFL_PATH.

root@a66aab345d9d:/mnt# export AFL_PATH=/mnt/AFLplusplus/

root@a66aab345d9d:/mnt# ./AFLplusplus/afl-cmin.bash -m none -U -i corpus_huge -o min_test_bash -- /usr/bin/python  on_data_recv_fuzzer.py @@

corpus minimization tool for afl-fuzz by Michal Zalewski



[*] Testing the target binary...

[+] OK, 1 tuples recorded.

[*] Obtaining traces for input files in 'corpus_huge'...

    Processing file 213/213...

[*] Sorting trace sets (this may take a while)...

[+] Found 1 unique tuples across 213 files.

[*] Finding best candidates for each tuple...

    Processing file 213/213...

[*] Sorting candidate list (be patient)...

[*] Processing candidates and writing output files...

    Processing tuple 1/1...

[!] WARNING: All test cases had the same traces, check syntax!

[+] Narrowed down to 1 files, saved in 'min_test_bash'.

**Comment by vanhauser-thc** [comment]
@korniltsev that is weird that afl-cmin.bash seem to have an issue - or I fucked something up in afl-showmap.

Is it possible that you create a zip with the corpus plus on_data_recv_fuzzer.py plus what else it needs to reproduce it? if it can be public you can attach it here, if not send it to me: vh@thc.org

**Comment by korniltsev** [comment]
The strange afl-cmin.bash result with 1 result file is reproducible with simple_test_harness.py
```
root@029abb8e4b80:/mnt/AFLplusplus/unicorn_mode/samples/simple# /mnt/AFLplusplus/afl-cmin -U -m none  -i o1/queue/ -o o1_min_awk  -- /usr/bin/python simple_test_harness.py @@
corpus minimization tool for afl++ (awk version)

Option m is only allowed once
[*] Testing the target binary...
[+] OK, 1 tuples recorded.
[*] Obtaining traces for 8 input files in 'o1/queue/'.
    Processing 8 files (forkserver mode)...[*] Spinning up the fork server...
[+] All right - fork server is up.

[*] Processing traces for input files in 'o1/queue/'.
    Processing file 8/8
[+] Found 12 unique tuples across 8 files.
[+] Narrowed down to 5 files, saved in 'o1_min_awk'.
root@029abb8e4b80:/mnt/AFLplusplus/unicorn_mode/samples/simple# /mnt/AFLplusplus/afl-cmin.bash -U -m none  -i o1/queue/ -o o1_min_bash  -- /usr/bin/python simple_test_harness.py @@
corpus minimization tool for afl-fuzz by Michal Zalewski

[*] Testing the target binary...
[+] OK, 1 tuples recorded.
[*] Obtaining traces for input files in 'o1/queue/'...
    Processing file 8/8...
[*] Sorting trace sets (this may take a while)...
[+] Found 1 unique tuples across 8 files.
[*] Finding best candidates for each tuple...
    Processing file 8/8...
[*] Sorting candidate list (be patient)...
[*] Processing candidates and writing output files...
    Processing tuple 1/1...
[!] WARNING: All test cases had the same traces, check syntax!
[+] Narrowed down to 1 files, saved in 'o1_min_bash'.
```

**Comment by korniltsev** [comment]
Here are two sets of my minimized corpus with AFL_KEEP_TRACES=1 [Archive.zip](https://github.com/vanhauser-thc/AFLplusplus/files/4219181/Archive.zip)

I can not share the fuzzer itself. Even privately. We better try to reproduce it with some sort of test, not my fuzzer.

**Comment by korniltsev** [comment]
[repro.zip](https://github.com/vanhauser-thc/AFLplusplus/files/4219389/repro.zip)

This test minimises to a different number of files. Did I make any mistake?

**Comment by hexcoder-** [comment]
Thanks. Will try to reproduce with repro.zip.
BTW: Archive.zip is incomplete (it lacks the .traces subdirectory, which repro.zip has)

**Comment by korniltsev** [comment]
@hexcoder- are you sure? it seems traces are there

**Comment by hexcoder-** [comment]
No, you are right. This stupid ubuntu decided to not show them to me.

**Comment by hexcoder-** [comment]
So, that should be fixed now with https://github.com/vanhauser-thc/AFLplusplus/commit/16a7e4ae681c45aadbba15bd32e7e1b5aeba2226. With your test data I was able to find the reasons for the deviations.

**Comment by hexcoder-** [comment]
@korniltsev Please confirm, thanks.

**Comment by korniltsev** [comment]
@hexcoder-  @domenukk  I confirm the fix in awk version. However cmin.bash is still broken for unicorn mode (see https://github.com/vanhauser-thc/AFLplusplus/issues/168#issuecomment-587436968)

**Comment by domenukk** [comment]
Thanks, that must be an unrelated issue, then. Debugging :)

**Comment by hexcoder-** [comment]
ok, to summarize, open points are now:
 1. more tests for afl-cmin on other platforms (arm (Raspberry Pi), x86 (*BSD and MacOSX))
 2. remove forkserver messages (low priority)
 3. at least understand the problem with unicorn on afl-cmin.bash (fixing it if that is wanted otherwise warn about it)

I would handle the first two items and leave item 3 to domenukk.

**Comment by domenukk** [comment]
Fixed item 3 with ed4a70c - the bug was introduced in https://github.com/vanhauser-thc/AFLplusplus/commit/1edc392194ee6fad60057dce4aa2c9b5e2099451#diff-77188d3c8933ecbbad0101d791f8cc9fL910 (`-A` for showmap was broken)

**Comment by vanhauser-thc** [comment]
I think item 2 does not need to be fixed. its nice to see the messages. I added the necessary linefeed and also fixed a bug if -o dir exists.

I found one discrepancy between afl-cmin and afl-cmin.bash ... afl-cmin will skip zero length files while afl-cmin.bash will not. I dont care which solution should be the right one, but it should be the same for both :)

**Comment by vanhauser-thc** [comment]
btw- with the afl-cmin awk script plus afl-showmap forkserver we have a speed increase of 5-10x versus the original afl-cmin.bash :)

**Comment by hexcoder-** [comment]
For item 1: tests completed successfully on MacOSX, RaspberryPi, NetBSD, FreeBSD, OpenBSD
For item 2: I fixed item 2 by making `afl-forkserver.c` obey `AFL_QUIET`. If this is not set, these lines can be seen as before.

BTW: Regarding performance, more is possible with caching traces. Greatest weakness of (n)awk is lack of sorting.
